GET http://localhost:3000
###
GET http://localhost:3000/users HTTP/1.1
###
GET http://localhost:3000/users/662790f2ef47a1b22376370f HTTP/1.1
###
POST  http://localhost:3000/users HTTP/1.1
Host: localhost
Content-Type: application/json
Authorization: Bearer your_access_token

{
    "name": "John foe",
    "email": "john.doe@example.com",
    "password": "password123"
}
###
POST  http://localhost:3000/users HTTP/1.1
Host: localhost
Content-Type: application/json
Authorization: Bearer your_access_token

{
    "name": "Siddhant Gupta",
    "email": "siddhantg2002@gmail.com",
    "password": "password123"
}
###
POST  http://localhost:3000/users HTTP/1.1
Host: localhost
Content-Type: application/json
Authorization: Bearer your_access_token

{
    "name": "Priyanka Mishra",
    "email": "Pri@Munchkin.com",
    "password": "password123"
}
###
DELETE http://localhost:3000/users/662790beef47a1b22376370d  

###
PATCH http://localhost:3000/users/662790beef47a1b22376370d
Content-Type: application/json

{
    "name": "Shashank Bhatele",
}